stages:
  - example (C++14) -- cppcheck, build (linux, gcc5), valgrind

notifications:
  email:
    on_success: never
    on_failure: always
    recipients:
      - karelburda89@gmail.com

jobs:
  include:
     - stage: example (C++14) -- cppcheck, build (linux, gcc5), valgrind
       sudo: required
       dist: trusty
       language: cpp
       compiler: g++
       os: linux
       addons:
         apt:
           sources:
             - ubuntu-toolchain-r-test
           packages:
             - g++-5
             - valgrind
             - cppcheck
       install: export CXX="g++-5"
       script:
         - set -e

         - cmake -Bbuild -H. -DEXAMPLE:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo
         - cppcheck --enable=all -I include --check-config  -v ./example
         - cmake --build build --target example --config RelWithDebInfo

         - set +e
