stages:
  - example and tests (C++14) -- cppcheck, build (linux, gcc5), valgrind, tests

jobs:
  include:
     - stage: example and tests (C++14) -- cppcheck, build (linux, gcc5), valgrind, tests
       sudo: required
       dist: trusty
       language: cpp
       compiler: g++
       os: linux
       addons:
         apt:
           sources:
             - ubuntu-toolchain-r-test
           packages:
             - g++-5
             - valgrind
             - cppcheck
       install: export CXX="g++-5"
       script:
         - set -e

         - cmake -Bbuild -H. -DEXAMPLE:BOOL=ON -DUNIT-TESTS:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo

         - cppcheck --enable=all -I include -I test-utils/include --check-config  -v ./example ./tests

         - cmake --build build --target example --config RelWithDebInfo

         - pushd ./build/bin/
         - valgrind --leak-check=full --error-exitcode=255 -v ./example
         - popd

         - cmake --build build --target run-all-tests-verbose --config RelWithDebInfo

         - set +e
