stages:
  - example and tests (C++14) -- cppcheck, build (linux, gcc5), valgrind, tests

jobs:
  include:
     - stage: example and tests (C++14) -- cppcheck, build (linux, gcc5), valgrind, tests
       sudo: required
       dist: trusty
       language: cpp
       compiler: g++
       os: linux
       addons:
         apt:
           sources:
             - ubuntu-toolchain-r-test
           packages:
             - g++-5
             - valgrind
             - cppcheck
       before_install:
         - pip install --user cpp-coveralls
       install: export CXX="g++-5"
       script:
         - set -e

         - cmake -Bbuild -H. -DEXAMPLE:BOOL=ON -DUNIT-TESTS:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo -DCOVERAGE:BOOL=ON

         - cppcheck --enable=all -I include -I test-utils/include --language=c++ --platform=unix64 --std=c++11 --check-config --suppress=missingIncludeSystem -v ./example ./tests

         - cmake --build build --target example --config RelWithDebInfo

         - pushd ./build/bin/
         - valgrind --leak-check=full --error-exitcode=255 -v ./example
         - popd

         - cmake --build build --target run-all-tests-verbose --config RelWithDebInfo
         - ls -la build && ls -la build/bin
         - coveralls -e ./build/gtest-src -e ./build/CMakeFiles -e ./tests/unit -e ./example --gcov-options '\-lp'

         - set +e
