stages:
  - function-loader, example, tests -- linux, debug, gcc, cppcheck, coverage
  - function-loader, example, tests -- osx, release with debug info, valgrind, clang

git:
  depth: 1

jobs:
  include:
     - stage: function-loader, example, tests -- linux, debug, gcc, cppcheck, coverage
       sudo: required
       dist: trusty
       language: cpp
       env: BUILD_TYPE="Debug"
       compiler: g++
       os: linux
       addons:
         apt:
           sources:
             - ubuntu-toolchain-r-test
           packages:
             - g++-6
             - cppcheck
       before_install:
         - pip install --user cpp-coveralls
       install: export CXX="g++-6"
       script:
         - set -e

         - cppcheck --enable=all
                    -I include
                    --language=c++
                    --platform=unix64
                    --std=c++11
                    --check-config
                    --suppress=missingIncludeSystem
                    -v ./tests

         - cmake -Bbuild -H. -DCMAKE_BUILD_TYPE:STRING=$BUILD_TYPE

         - cmake -Bbuild/example -Hexample -Dfunction-loader_DIR:PATH=$(pwd)/build -DCMAKE_BUILD_TYPE:STRING=$BUILD_TYPE
         - cmake --build build/example --config $BUILD_TYPE

         - cmake -Bbuild/submodules/test-utils -Hsubmodules/test-utils -DCMAKE_BUILD_TYPE:STRING=$BUILD_TYPE
         - cmake -Bbuild/tests/unit -Htests/unit
                 -Dfunction-loader_DIR:PATH=$(pwd)/build
                 -Dtest-utils_DIR:PATH=$(pwd)/build/submodules/test-utils
                 -DCMAKE_BUILD_TYPE:STRING=$BUILD_TYPE
                 -DCOVERAGE:BOOL=ON
         - cmake --build build/tests/unit --target run-all-tests-verbose --config $BUILD_TYPE

         - bash <(curl -s https://codecov.io/bash)

         - set +e

     - stage: function-loader, example, tests -- osx, release with debug info, valgrind, clang
       os: osx
       language: cpp
       env: BUILD_TYPE="RelWithDebInfo"
       compiler: clang
       before_install:
         - HOMEBREW_NO_AUTO_UPDATE=1 brew install valgrind
       script:
         - set -e

         - cmake -Bbuild -H. -DCMAKE_BUILD_TYPE:STRING=$BUILD_TYPE

         - cmake -Bbuild/example -Hexample -Dfunction-loader_DIR:PATH=$(pwd)/build -DCMAKE_BUILD_TYPE:STRING=$BUILD_TYPE
         - cmake --build build/example --config $BUILD_TYPE
         - valgrind --leak-check=full --error-exitcode=255 -v ./build/example/example

         - cmake -Bbuild/submodules/test-utils -Hsubmodules/test-utils -DCMAKE_BUILD_TYPE:STRING=$BUILD_TYPE
         - cmake -Bbuild/tests/unit -Htests/unit
                 -Dfunction-loader_DIR:PATH=$(pwd)/build
                 -Dtest-utils_DIR:PATH=$(pwd)/build/submodules/test-utils
                 -DCMAKE_BUILD_TYPE:STRING=$BUILD_TYPE
                 -DCOVERAGE:BOOL=ON
         - cmake --build build/tests/unit --target run-all-tests-verbose --config $BUILD_TYPE

         - set +e
